// reactjs/src/App.jsx
import { Heading, Button, Wrapper } from "js-ui-clevai";

const App = () => {
  return (
    <>
      <Wrapper type="react" id="ducdc" className="dochiduc" pd={{ t: 20 }} mg={{ b: 40 }} bg="green4" br="9" w={400.5}>
        qweqe
      </Wrapper>
      <Heading type="react" tag="h2" font="semibold" color="green8" onClick={() => console.log("first")}>
        ducdc
      </Heading>
      <Button type="react" category="default" size="lg" color="otherRoyalBlue" onClick={() => console.log("first")}>
        ducdc
      </Button>
    </>
  );
};

export default App;

// vuejs/src/App.vue
<template>
  <Wrapper
    :type="'vue'"
    :id="'ducdc'"
    :className="'dochiduc'"
    :mg="{ t: 30 }"
    :pd="{ r: 20, b: 30 }"
    :br="'10'"
    :bg="'blue6'"
    @click="console.log('ducdc')"
    >ppppp</Wrapper
  >
  <Heading :type="'vue'" :tag="'h1'" :color="'otherElectricViolet'" :font="'semibold'">sss</Heading>
  <Button :type="'vue'" :category="'link'" :size="'md'">ducdc</Button>
</template>

<script setup>
import { Heading, Button, Wrapper } from "js-ui-clevai";
</script>
